"use client";
import { useEffect, useState } from "react";
import { useRouter, useParams } from "next/navigation";
import { useSession } from "next-auth/react";
import { useForm } from "react-hook-form";
import { zodResolver } from "@hookform/resolvers/zod";
import { toast } from "sonner";
import Link from "next/link";
import { updateBorrowSchema } from "@/lib/validations/borrow";
import FormField from "@/components/forms/FormField";
const STATUSES=[{value:"pending",label:"Очікує"},{value:"issued",label:"Видано"},{value:"returned",label:"Повернено"},{value:"overdue",label:"Прострочено"},{value:"cancelled",label:"Скасовано"}];
export default function EditBorrowPage(){const router=useRouter();const params=useParams();const {data:session,status:sessionStatus}=useSession();const [borrow,setBorrow]=useState(null);const [loading,setLoading]=useState(true);const {register,handleSubmit,reset,formState:{errors,isSubmitting}}=useForm({resolver:zodResolver(updateBorrowSchema),defaultValues:{status:"pending",notes:""}});useEffect(()=>{fetch(`/api/borrows/${params.id}`).then(r=>r.json()).then(d=>{if(d.error){setLoading(false);return;}setBorrow(d);reset({status:d.status,notes:d.notes||""});setLoading(false);}).catch(()=>setLoading(false));},[params.id,reset]);if(sessionStatus==="loading"||loading)return <div>Завантаження...</div>;if(session?.user?.role!=="admin")return <div className="bg-red-50 border border-red-200 text-red-700 px-6 py-4 rounded">Редагувати видачі може лише адміністратор.</div>;if(!borrow)return <div className="bg-red-50 border border-red-200 text-red-700 px-6 py-4 rounded">Видачу не знайдено</div>;const onSubmit=async(data)=>{try{const res=await fetch(`/api/borrows/${params.id}`,{method:"PUT",headers:{"Content-Type":"application/json"},body:JSON.stringify(data)});const body=await res.json().catch(()=>({}));if(!res.ok)throw new Error(body.errors?.join(", ")||body.error||"Помилка збереження");toast.success("Видачу оновлено");router.push(`/dashboard/borrows/${params.id}`);router.refresh();}catch(e){toast.error(e.message);}};return <div className="max-w-2xl"><Link href={`/dashboard/borrows/${params.id}`} className="text-amber-700 hover:underline mb-4 inline-block">← Назад до видачі</Link><h1 className="text-3xl font-bold mb-6">Редагування видачі</h1><form onSubmit={handleSubmit(onSubmit)} className="bg-white p-6 rounded-lg shadow space-y-5"><FormField label="Статус" required error={errors.status?.message}><select {...register("status")} className="w-full px-4 py-2 border rounded">{STATUSES.map(s=><option key={s.value} value={s.value}>{s.label}</option>)}</select></FormField><FormField label="Коментар" error={errors.notes?.message}><textarea rows="3" maxLength={300} {...register("notes")} className="w-full px-4 py-2 border rounded" /></FormField><button type="submit" disabled={isSubmitting} className="bg-amber-700 text-white px-6 py-3 rounded font-bold disabled:opacity-50">{isSubmitting?"Збереження...":"Зберегти"}</button></form></div>}
